#ifndef VERMOGENSKRIEGER_GLOBAL_H
#define VERMOGENSKRIEGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VERMOGENSKRIEGER_LIBRARY)
#define VERMOGENSKRIEGER_EXPORT Q_DECL_EXPORT
#else
#define VERMOGENSKRIEGER_EXPORT Q_DECL_IMPORT
#endif

#endif // VERMOGENSKRIEGER_GLOBAL_H
