#ifndef LOGIN_H
#define LOGIN_H

#include <QWidget>
#include <QPushButton>
#include <QLabel>

namespace Ui {
class Login;  // Forward declaration for the UI class generated by Qt Designer
}

class Login : public QWidget {
    Q_OBJECT

public:
    explicit Login(QWidget *parent = nullptr);
    ~Login();

signals:
    void loginSuccessful();  // Signal emitted on successful login

private slots:
    void on_loginButton_clicked(); // Slot for handling login button click

private:
    Ui::Login *ui;             // Pointer to the UI
    int failedAttempts;        // Counter for failed login attempts

    bool verifyCredentials(const QString &username, const QString &password); // Function to verify credentials
};

#endif // LOGIN_H
